export const FIELDS: any = {
    "total_cases": "összes eset",
    "new_cases": "új esetek",
    "new_cases_smoothed": "új esetek (mozgóátlag)",
    "total_deaths": "összes haláleset",
    "new_deaths": "új halálesetek",
    "new_deaths_smoothed": "új halálesetek (mozgóátlag)",
    "total_cases_per_million": "összes eset 1 millió lakosra",
    "new_cases_per_million": "új esetek 1 millió lakosra",
    "new_cases_smoothed_per_million": "új esetek (mozgóátlag) 1 millió lakosra",
    "total_deaths_per_million": "összes haláleset 1 millió lakosra",
    "new_deaths_per_million": "új halálesetek 1 millió lakosra",
    "new_deaths_smoothed_per_million": "új halálesetek (mozgóátlag) 1 millió lakosra",
    "total_tests": "összes teszt",
    "new_tests": "új tesztek",
    "new_tests_smoothed": "új tesztek (mozgóátlag)",
    "total_tests_per_thousand": "összes teszt ezer lakosra",
    "new_tests_per_thousand": "új tesztek ezer lakosra",
    "new_tests_smoothed_per_thousand": "új tesztek (moozgóátlag) ezer lakosra",
    "tests_per_case": "egy pozitív esetre jutó tesztek száma",
    "positive_rate": "pozitív tesztek aránya",
    "tests_units": "tesztelő egységek",
  }